name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: bazel build /${{ matrix.dir }}:${{ matrix.name }} (on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        dir: [/main]
        name: [recursion]

    steps:
      - uses: actions/checkout@v3

      - name: Cache bazel
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
            /private/var/tmp/_bazel_runner/
            %HOME%
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('.bazelrc', '.bazelversion', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}

      - name: Build code
        run: bazel --output_base=./build build /${{ matrix.dir }}:${{ matrix.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}
          path: |
            bazel-bin
            main
