name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: /${{ matrix.dir }}:${{ matrix.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        dir: [/main]
        name: [recursion]

    steps:
      - uses: actions/checkout@v3

      - name: Cache bazel
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            bazel-bin
            bazel-${{ github.event.repository.name }}/*
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}

      - name: Build code
        run: bazel build /${{ matrix.dir }}:${{ matrix.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}
          path: |
            bazel-bin
            ${{ matrix.dir }}
