name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - uses: actions/checkout@v2

      # build
      - name: Build Code
        run: bazel build //main:hello-world
      # - name: Run tests
      #   run: bazel test //...