name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Cache bazel
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: ./build
          key: ${{ env.cache-name }}-${{ runner.os }}

      - name: Build code
        run: bazel build --output_base=./build //main:recursion

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}
          path: bazel-bin
