name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - uses: actions/checkout@v3

      # build
      - name: Build Code
        run: bazel build //main:hello-world
      # - name: Run tests
      #   run: bazel test //...
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}
          path: bazel-bin
